# Generated by Django 5.1.2 on 2024-12-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_prices_botpayment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpayment',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botpayment',
            name='action_id',
            field=models.IntegerField(default=-1),
        ),
    ]
