# Generated by Django 5.1.2 on 2024-12-02 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('finance', '0003_botpayment_status_alter_botpayment_action_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_off', models.BooleanField()),
                ('amount', models.PositiveIntegerField()),
                ('customer_count', models.PositiveIntegerField()),
                ('use_count', models.PositiveIntegerField()),
                ('create_timestamp', models.PositiveBigIntegerField()),
                ('end_timestamp', models.PositiveBigIntegerField()),
                ('for_infinit_usages', models.BooleanField()),
                ('for_infinit_times', models.BooleanField()),
                ('for_not_infinity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActiveOffCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('off_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.offcodes')),
            ],
        ),
    ]
