# Generated by Django 5.1.2 on 2024-12-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_offcodes_useractiveoffcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botpayment',
            name='action_id',
        ),
        migrations.AddField(
            model_name='botpayment',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
