# Generated by Django 5.1.2 on 2024-12-16 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_sellersprices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('type', models.SmallIntegerField(choices=[(0, 'buy'), (1, 'renew'), (2, 'pay')], default=0)),
                ('description', models.CharField(max_length=120)),
                ('date_time', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P_created_by', to=settings.AUTH_USER_MODEL)),
                ('created_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P_created_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
