# Generated by Django 5.1.2 on 2024-12-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_purchaserecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='service_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
