# Generated by Django 5.1.2 on 2025-01-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_purchaserecord_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpayment',
            name='service_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
