# Generated by Django 5.1.2 on 2024-12-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bot', '0002_sellerbots'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.sellerbots'),
        ),
    ]
