# Generated by Django 5.1.2 on 2024-12-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_disable_config_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disable_config_acc',
            field=models.BooleanField(default=True),
        ),
    ]
