# Generated by Django 5.1.2 on 2024-12-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_disable_config_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='finanace_access',
            new_name='finance_access',
        ),
    ]
