# Generated by Django 5.1.2 on 2024-12-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_finanace_access_user_finance_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand',
            field=models.CharField(default='Service', max_length=20),
        ),
    ]
