# Generated by Django 5.1.2 on 2024-12-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='maximum_connection',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
