# Generated by Django 5.1.2 on 2024-12-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_active_server_maximum_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_update',
            field=models.BigIntegerField(default=0),
        ),
    ]
