# Generated by Django 5.1.2 on 2024-12-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='online_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
