# Generated by Django 5.1.2 on 2025-01-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_server_online_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='ID',
            new_name='id',
        ),
    ]
