# Generated by Django 5.1.2 on 2025-02-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_rename_id_server_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='fake_domain',
        ),
        migrations.RemoveField(
            model_name='server',
            name='inbound_port',
        ),
        migrations.AddField(
            model_name='server',
            name='config_example',
            field=models.TextField(default=''),
        ),
    ]
