# Generated by Django 5.1.2 on 2025-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_remove_server_fake_domain_remove_server_inbound_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='copy_in_link',
            field=models.BooleanField(default=True),
        ),
    ]
