# Generated by Django 5.1.2 on 2024-12-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage_limit', models.IntegerField(default=0)),
                ('expire_time', models.BigIntegerField(default=0)),
                ('user_limit', models.SmallIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('usage', models.BigIntegerField(default=0)),
                ('last_update', models.BigIntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.service')),
            ],
        ),
    ]
