# Generated by Django 5.1.2 on 2024-12-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ConfigJobsQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField(choices=[(0, 'create'), (1, 'disable'), (2, 'delete'), (3, 'enable'), (4, 'reset')])),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.config')),
            ],
        ),
    ]
