# Generated by Django 5.1.2 on 2024-12-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_alter_service_paid_configjobsqueue'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configjobsqueue',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configjobsqueue',
            name='last_try',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configjobsqueue',
            name='try_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sellers.seller'),
        ),
    ]
