# Generated by Django 5.1.2 on 2024-12-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_configjobsqueue_done_configjobsqueue_last_try_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'creating'), (1, 'active'), (2, 'disable'), (3, 'deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'disable'), (2, 'Ended'), (4, 'deleting')], default=0),
        ),
    ]
