# Generated by Django 5.1.2 on 2024-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_alter_config_status_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'not_created'), (1, 'active'), (2, 'disable'), (3, 'deleted')], default=-1),
        ),
    ]
