# Generated by Django 5.1.2 on 2024-12-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0006_alter_config_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='usage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='config',
            name='usage',
            field=models.FloatField(default=0),
        ),
    ]
