# Generated by Django 5.1.2 on 2024-12-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_service_usage_alter_config_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
