# Generated by Django 5.1.2 on 2024-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0008_service_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='usage_limit',
            field=models.FloatField(default=0),
        ),
    ]
