# Generated by Django 5.1.2 on 2024-12-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0012_alter_service_created_by_alter_service_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndNotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveBigIntegerField()),
                ('type', models.SmallIntegerField(choices=[(0, 'ended'), (1, 'time'), (2, 'usage')])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.service')),
            ],
        ),
    ]
