# Generated by Django 5.1.2 on 2025-01-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0014_configjobsqueue_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
