# Generated by Django 5.1.2 on 2025-06-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0015_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='infinit_limit',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
