# Generated by Django 5.1.2 on 2025-06-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0016_service_infinit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='new_version',
            field=models.BooleanField(default=True),
        ),
    ]
