# Generated by Django 5.1.2 on 2024-12-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('wallet', models.IntegerField(default=0)),
                ('purchase_number', models.PositiveIntegerField(default=0)),
                ('test_config', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('banned', models.BooleanField(default=False)),
            ],
        ),
    ]
