# Generated by Django 5.1.2 on 2024-12-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_name'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerylog',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
