# Generated by Django 5.1.2 on 2025-01-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0015_service_price'),
        ('customers', '0003_alter_customer_name'),
        ('logs', '0002_celerylog_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timestamp', models.PositiveBigIntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timestamp', models.PositiveBigIntegerField()),
                ('sevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.service')),
            ],
        ),
    ]
