# Generated by Django 5.1.2 on 2025-01-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_customerlog_servicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerylog',
            name='tag',
            field=models.PositiveIntegerField(choices=[(0, 'delete completely'), (1, 'create'), (2, 'delete service'), (3, 'delete'), (4, 'enable'), (5, 'disable')], default=0),
        ),
    ]
